### ISSUE TITLE
Block Reward

### ISSUE THREAD

**Issue by BKdilse** [GNTLMiningPools/gntl#4]
Need to agree block reward

**Comment by thetobby** [comment]
I would suggest borrowing from the original CCX distribution model prepared by their economist.

Coin production start from 5, will increase by 0.25 every month to reach 15, then will decrease by 0.10 every month to 6 and will be fixed there.(Dromedary model)

This prevents the first miners from owning most of the coin. In addition, as the recognition of the coin increases, the gradual increase in the supply ensures that the coins produced are spread to the community more healthily.

**Comment by BKdilse** [comment]
Thanks for the input, it will be considered.

**Comment by tylerjohneddy** [comment]
That's an interesting way to go about it. So would take alittle over 3 years to hit the 15 mark
Then 7.5 years to get down to 6

Would give us plenty of time to promote the coin and incentivise new comers

**Comment by BKdilse** [comment]
Agreed reward starting at 50 GNTL.

**Comment by BKdilse** [comment]
All change, we're going with 66.6 to wallet, so Gov is already removed.
