### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by BKdilse** [GNTLMiningPools/gntl#5]
Agree Governance fee, decreasing at hard forks

**Comment by tylerjohneddy** [comment]
I suggest that the governance starts at its highest point and drops over set months

**Comment by BKdilse** [comment]
Agreed Governance:

10% 3 months, 5% for 6 months, then 1% forever.

**Comment by BKdilse** [comment]
Gov Fee round up:

```
10% until height 87000
5% until height 260000
1% there on
```

**Comment by BKdilse** [comment]
Tested change on Stagenet using lower block heights, can confirm percentage changes work fine.
